# Starts a docker container running a minio server instance.
# Four virtual volumes are shown.
# Do not do this in production!
services:
  minio1:
    image: quay.io/minio/minio
    command: server --console-address ":9090" /data
    ports:
      - "9050:9000"
      - "9051:9090"
    container_name: minio1
    volumes:
      - /tmp/data/minio:/data

  minio2:
    image: quay.io/minio/minio
    command: server --console-address ":9090" /data
    ports:
      - "9052:9000"
      - "9053:9090"
    container_name: minio2
    volumes:
      - /tmp/data/minio:/data
