# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio
  command: server --console-address ":9090" /data
  expose:
    - "9000"
    - "9090"
  environment:
    MINIO_ROOT_USER: "minioadmin"
    MINIO_ROOT_PASSWORD: "minioadmin"

# Starts a docker container running a minio server instance.
# Four virtual volumes are shown.
# Do not do this in production!
services:
  minio1:
    <<: *minio-common
    ports:
      - "9050:9000"
      - "9051:9090"
    container_name: minio1
    hostname: minio1
    volumes:
      - /tmp/data/minio1:/data
