# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" data1
  expose:
    - "9000"
    - "9090"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 1 docker container running minio server instances.
services:
  minio1:
    <<: *minio-common
    hostname: minio-docker-compose
    volumes:
      - /tmp/data/docker-compose-data:/data1
    ports:
      - "9000:9000"
      - "9090:9090"
